[env]
TERM = "xterm-256color"

# [terminal.shell]
# program = "/bin/fish"
# program = "zellij"
# args = ["-l", "welcome"]

[general]
live_config_reload = true

import = ["~/.config/alacritty/themes/themes/everblush.toml"]

[window]
dynamic_padding = false
# opacity = 0.8
# blur = true

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size = 16.0

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "On" }
