vim.cmd([[set number]])
vim.cmd([[set ruler]])
vim.cmd([[set autoindent]])
vim.cmd([[set mouse=a]])
vim.cmd([[set tabstop=4]])
vim.cmd([[set shiftwidth=4]])
vim.cmd([[set hlsearch]])
vim.cmd([[set relativenumber]])

require("seba.lazy")
